### ISSUE TITLE
Feature request: Allow `allowed_audiences` to be empty tuple

### ISSUE THREAD

**Issue by KonStg** [Cyclenerd/terraform-google-wif-gitlab#5]
Type should be `list(string)`, not string.
Default value should be `[ "https://gitlab.com" ]`, not `https://gitlab.com`.

This changes allow us to use default value (which is empty tuple `[]` see https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/iam_workload_identity_pool_provider#allowed_audiences) for cases when `id_token:TOKEN_NAME:aud` is specified explicitly with `module.gitlab-wif.provider_name` (from "Cyclenerd/wif-gitlab/google")

**Comment by Cyclenerd** [comment]
You mean list(string), right? Why do you want to pass it empty?
